### ISSUE TITLE
Can't cut audio

### ISSUE THREAD

**Issue by tuanden0** [AzraelNewtype/audiocutter#1]
Hi Sir,
I tried to use audiocutter to cut audio but it didn't work
Here's my script:

`
import vapoursynth as vs
import audiocutter
import sys, os
sys.path.append(os.getenv('APPDATA') + r"\VapourSynth\scripts")

source = r"E:\Download\Source\test.mkv"
core = vs.core
clip = core.ffms2.Source(source)
clip = core.std.AssumeFPS(clip, fpsnum=24000, fpsden=1001)
ac = audiocutter.AudioCutter()
clip = ac.split(clip, [(0,100),(200,300)])
clip.set_output()

if __name__ == "__main__":
    prefix = os.path.splitext(__file__)[0]
    ac.cut_audio(outfile=prefix + '_aud_ac.mka', video_source=source)
    
`

When I run it, they still say: "Cannot find audio file that matches given video file name"
Even if I change location of mkvmerge in audiocutter.py, they still not work.

My MKVToolnix is newest and location: "E:\Soft\mkvtoolnix\mkvmerge.exe"
And here's what I changed: "self.__mkvmerge = r'E:/Soft/mkvtoolnix/mkvmerge.exe' "
And when I change video_source=source to audio_source=source:
`Traceback (most recent call last):
  File "E:\Download\Source\GGO\f.py", line 16, in <module>
    ac.cut_audio(outfile=prefix + '_aud_ac.mka', audio_source=source)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\site-packages\audiocutter.py", line 210, in cut_audio
    ident = check_output([self.__mkvmerge, "--identify-for-mmg", afile])
  File "C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['E:/Soft/mkvtoolnix/mkvmerge.exe', '--identify-for-mmg', 'E:\\Download\\Source\\test.mkv']' returned non-zero exit status 2.`

**Comment by AzraelNewtype** [comment]
`video_source` means you have a an audio file with roughly the same name as the video name, not that the source is actually a video. Extract the audio and pass that filename to `audio_source`.

**Comment by tuanden0** [comment]
Hi Sir,

I found the problem. Since mkvtoolnix version 20, the parameter "--identify-for-mmg" was remove and changed to "--identify"

> https://mkvtoolnix.download/doc/NEWS.md

> # Version 20.0.0 "I Am The Sun" 2018-01-15

## Important notes

* Feature removal: several deprecated features have been removed:

  * mkvmerge: the deprecated options `--identify-verbose` (and its counterpart
    `-I`), `--identify-for-gui`, `--identify-for-mmg` and
    `--identification-format verbose-text`
